name: Golang CI
on:
  # Triggers the workflow on push or pull request events but only for the master and tags branch
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check_and_build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
